### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by DmT2022** [0kev0/SYP_Sistema_Colegio_JNSP#1]
__Implementar frame de secretarias__
- [x] > inventario/venta uniformes y libros
- [x] > gestión matricula
- [x] > gestión mensualidades
- [x] > gestión inscripciones

__Implementar frame Director__
- [ ] > Gestion de matriculas, mensualidades, inventarios, inscripciones 

_Frames de docente_

> Regitro notas, 
- [x] >Error providers para el tb_buscar para solo num o texto
- [x] >Agregar try catch

>Asignacion de actividades,
- [x] >Insert de actividades
- [x] .validacion de numero de actividades por periodo
- [x] >validacion de tipo de actividad 4 tareas 1 examen 1 autoevaluacion
- [x] >validar tb_descricion y tb_nombre actividad
- [x] >funcion para editar actividades

>Asignar notas
- [x] #2
- [x] >implementar filtro de tipo de actividad
- [x] >implementar buscadores
- [x] >implementar edicion de notas

>toma asistencia
- [x] >ultimas validaciones

>Registro asistencia
- [x] >filtro por dia
- [ ] >que el cb_dia cambie segun numero de dias del mes
- [x] >resumen de asistencias de un alumno al dar clic a su fila, incluira dias asisteidos, ausencias y ausencias justificadas con la justificacion dada
- [x] >buscador por nie,nombre o apellido
- [x] >edicion de sistencia por dia 

>Modificar cuenta

>tbl_notas finales
- [ ] >col NIE|nombre/apellido|T1|T2TT31T4| PROM FINAL

>Notas finales
- [ ] > get notas finales de tbl_notasfinales
- [ ] >insert trimestre a tbl_notas finales
- [ ] >llenar plantilla excel con trimestre a llenar y trimestres completados(el promedio)

- [ ] > revisar a la hr de inscribir por inscripción nueva y por reinscripcion
